name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.0
  url_launcher: ^6.1.10
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+2
  path_provider: ^2.1.1
  image_picker: ^0.8.6
  path: ^1.8.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
